### ISSUE TITLE
Test Fail (Error: could not locate database directory.\n)

### ISSUE THREAD

**Issue by erfanshekarriz** [allind/EukDetect#31]
Hello, I'm following the instructions precisely installing EukDetect, but the test gives me the following error: 

```
(eukdetect)python tests/test_eukdetect.py
.FFF.
======================================================================
FAIL: test_class (__main__._02_RunRunall)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_eukdetect.py", line 26, in test_class
    self.assertTrue(code==0, msg=stderr)
AssertionError: False is not true : b'11/06/2022 07:19:26:  Parsing config file ...\n11/06/2022 07:19:26:  Error: could not locate database directory.\n'

======================================================================
FAIL: test_class (__main__._03_RunAlnCmd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_eukdetect.py", line 33, in test_class
    self.assertTrue(code==0, msg=stderr)
AssertionError: False is not true : b'11/06/2022 07:19:26:  Parsing config file ...\n11/06/2022 07:19:26:  Error: could not locate database directory.\n'

======================================================================
FAIL: test_class (__main__._04_RunAln_and_filter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_eukdetect.py", line 44, in test_class
    self.assertTrue(alncode==0 and filtercode == 0, msg=alnstderr + filterstderr)
AssertionError: False is not true : b'11/06/2022 07:19:26:  Parsing config file ...\n11/06/2022 07:19:26:  Error: could not locate database directory.\n11/06/2022 07:19:27:  Parsing config file ...\n11/06/2022 07:19:27:  Error: could not locate database directory.\n'

----------------------------------------------------------------------
Ran 5 tests in 1.298s
```

Any quick fixes on this?

Best, 

Erfan

**Comment by allind** [comment]
Hi Erfan,

In the test config file that you're using, what's the database directory you've specified? It looks like it's not readable.

Best,
Abigail

**Comment by erfanshekarriz** [comment]
Dear Abigail, 

Thank you for your prompt reply. The issue has been resolved by altering the config file in the test directory. Completely missed that part of the instructions. My bad. 

Best, 

Erfan
