### ISSUE TITLE
ModuleNotFoundError: No module named 'datrie'

### ISSUE THREAD

**Issue by fuesseler** [allind/EukDetect#40]
Hello,

Thanks for creating this pipeline! Unofrtunately, I have issues getting it to run on HPC environment (Slurm).
Snakemake scripts are unable to find packages that were installed using conda:

Command:
```
source activate ~/miniconda3/envs/eukdetect
export PYTHONPATH=$PYTHONPATH:/home/miniconda3/envs/eukdetect/lib/python3.6/site-packages
eukdetect --mode runall --configfile my_configfile.yml --cores 20

```

Error:

`Traceback (most recent call last):
  File "/home/miniconda3/envs/eukdetect/lib/python3.6/site-packages/snakemake/__init__.py", line 476, in snakemake
    success = workflow.execute(
  File "/home/miniconda3/envs/eukdetect/lib/python3.6/site-packages/snakemake/workflow.py", line 377, in execute
    dag = DAG(
  File "/home/miniconda3/envs/eukdetect/lib/python3.6/site-packages/snakemake/dag.py", line 116, in __init__
    self.update_output_index()
  File "/home/miniconda3/envs/eukdetect/lib/python3.6/site-packages/snakemake/dag.py", line 209, in update_output_index
    self.output_index = OutputIndex(self.rules)
  File "/home/miniconda3/envs/eukdetect/lib/python3.6/site-packages/snakemake/output_index.py", line 16, in __init__
    import datrie
ModuleNotFoundError: No module named 'datrie'
`
 datrie is installed under site-packages of the environment, but under the name "datrie.cpython-36m-x86_64-linux-gnu.so"

Do you have an idea how to fix this issue?

**Comment by allind** [comment]
Thanks for reaching out. How did you install snakemake? Googling this error, I see some people have run into it when installing snakemake via pip instead of via conda. Can you try installing snakemake via conda?
